default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: tk
  password: tk
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

development:
  <<: *default
  database: property_onboarding_development

test:
  <<: *default
  database: property_onboarding_test

production:
  <<: *default
  database: property_onboarding_production
  username: property_onboarding
  password: <%= ENV["PROPERTY_ONBOARDING_DATABASE_PASSWORD"] %>
